### ISSUE TITLE
I tried to run rvgpu renderer using 'gem' and encountered some issues. can you tell me how to run it?

### ISSUE THREAD

**Issue by Vizdl** [unified-hmi/remote-virtio-gpu#12]
I run the following command on the first window :
`sudo rvgpu-renderer -g /dev/dri/card0 -b 800x600@0,0 -p 55667`

Run the following command in the second window
```bash
su
modprobe virtio-gpu
modprobe virtio_lo
mkdir -p /run/user/4 && \
export XDG_RUNTIME_DIR=/run/user/4 && \
rvgpu-proxy -s 800x600@0,0 -n 127.0.0.1:55667 &

export LD_LIBRARY_PATH=/usr/lib/mesa-virtio  && glmark2-es2
```

The following prompt appears in the first window
```bash
rvgpu-renderer: Connector 36, resolution 2358x1278, vsync 60
libinput info: event0  - Power Button: is tagged by udev as: Keyboard
libinput info: event0  - Power Button: device is a keyboard
libinput info: event4  - VMware VMware Virtual USB Mouse: is tagged by udev as: Mouse
libinput info: event4  - VMware VMware Virtual USB Mouse: device is a pointer
libinput info: event1  - AT Translated Set 2 keyboard: is tagged by udev as: Keyboard
libinput info: event1  - AT Translated Set 2 keyboard: device is a keyboard
libinput info: event3  - VirtualPS/2 VMware VMMouse: is tagged by udev as: Mouse
libinput info: event3  - VirtualPS/2 VMware VMMouse: device is a pointer
libinput info: event2  - VirtualPS/2 VMware VMMouse: is tagged by udev as: Mouse
libinput info: event2  - VirtualPS/2 VMware VMMouse: device is a pointer
gl_version 0 - compat profile
WARNING: running without ARB/KHR robustness in place may crash
rvgpu-renderer: ../src/dispatch_common.c:863: epoxy_get_proc_address: Assertion `0 && "Couldn't find current GLX or EGL context.\n"' failed.
```
The second window displays using software rendering
```bash
gbm: failed to open any driver (search paths /usr/lib/mesa-virtio/dri)
gbm: Last dlopen error: /usr/lib/mesa-virtio/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory
failed to load driver: vmwgfx
=======================================================
    glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     VMware, Inc.
    GL_RENDERER:   llvmpipe (LLVM 16.0, 128 bits)
    GL_VERSION:    OpenGL ES 3.0 Mesa 18.2.0
=======================================================
```

**Comment by FumiyaKohzu** [comment]
Thank you for your comment. 

It seems that the initialization of OpenGLES is failing according to the rvgpu-renderer log. Can you launch glmark2 **without using remote-virtio-gpu?**

Additionally, remote-virtio-gpu supports Ubuntu 20.04 LTS AMD64. Please let me know your operating environment.

Thank you.

**Comment by Vizdl** [comment]
> 感谢您的评论。
> 
> 根据 rvgpu-renderer 日志，OpenGLES 的初始化似乎失败。您可以在不使用remote-virtio-gpu的情况下启动glmark2吗**？**
> 
> 此外，remote-virtio-gpu 支持 Ubuntu 20.04 LTS AMD64。请告知您的运行环境。
> 
> 谢谢。

我的环境如下
My environment is as follows
```bash
root@ubuntu:~$ uname -a
Linux ubuntu 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
I used vmware to run it. this seems to cause the call to eglcreatecontext to fail.
If you modify the version of 'ctxattr', you can successfully create a context, but there will still be other issues.
eg : 
from 
```c
EGLint ctxattr[] = { 
  EGL_CONTEXT_MAJOR_VERSION_KHR, 3,
  EGL_CONTEXT_MINOR_VERSION_KHR, 0, 
  EGL_NONE
};
```
to
```c
EGLint ctxattr[] = { 
  EGL_CONTEXT_MAJOR_VERSION_KHR, 2,
  EGL_CONTEXT_MINOR_VERSION_KHR, 0, 
  EGL_NONE
};
```

**Comment by Vizdl** [comment]
> 感谢您的评论。
> 
> 根据 rvgpu-renderer 日志，OpenGLES 的初始化似乎失败。您可以在不使用remote-virtio-gpu的情况下启动glmark2吗**？**
> 
> 此外，remote-virtio-gpu 支持 Ubuntu 20.04 LTS AMD64。请告知您的运行环境。
> 
> 谢谢。

**Comment by Vizdl** [comment]
> 我们已经在本机 Ubuntu 上测试了 Remote-virtio-gpu 的运行，但尚未验证其在 VMware 上的性能。因此，我们不能保证remote-virtio-gpu能够在VMware上运行。
> 
> RVGPU 需要 OpenGLES 3.0 或更高版本，但由于 glmark2 结果显示“OpenGL 4.1”，因此您似乎无法在您的环境中使用 OpenGLES 3.0。即使执行 `sudo apt install libgles2-mesa-dev ` README中提到的命令，如果仍然无法使用OpenGLES 3.0，则有可能VMware不支持OpenGLES 3.0。 在这种情况下，我们恳请您准备一个可以通过其他方式使用 OpenGLES 3.0 的环境。
> 
> 谢谢。

I have run smoothly using the physical machine environment, and perhaps I need to do some adaptation operations on vmware. Thank you for your answer!

**Comment by Vizdl** [comment]
> > 我们已经在本机Ubuntu上测试了Remote-virtio-gpu的运行，但尚未验证其在VMware上的性能。因此，我们不能保证remote-virtio-gpu能够在VMware上运行。
> > RVGPU 需要 OpenGLES 3.0 或更高版本，但由于 glmark2 结果显示“OpenGL 4.1”，因此您似乎无法在您的环境中使用 OpenGLES 3.0。即使执行 README 中提到的命令，如果仍然无法使用 OpenGLES 3.0，则`sudo apt install libgles2-mesa-dev `有可能VMware不支持OpenGLES 3.0。在这种情况下，我们恳请您准备一个可以通过其他方式使用OpenGLES 3.0的环境。
> > 谢谢。
> 
> 我使用物理机环境运行顺利，也许还需要在vmware上做一些适配操作。谢谢您的回答！

I have run smoothly using the physical machine environment, and perhaps I need to do some adaptation operations on vmware. Thank you for your answer!

**Comment by Vizdl** [comment]
> > > 我们已经在本机Ubuntu上测试了Remote-virtio-gpu的运行，但尚未验证其在VMware上的性能。因此，我们不能保证remote-virtio-gpu能够在VMware上运行。 RVGPU需要OpenGLES 3.0或
> > > 更高版本，但由于 glmark2 结果显示“OpenGL 4.1”，因此您似乎无法在您的环境中使用 OpenGLES 3.0。即使执行 README 中提到的命令，如果仍然无法使用 OpenGLES 3.0，则可能 VMware 不支持 OpenGLES 3.0 `sudo apt install libgles2-mesa-dev `。在这种情况下，我们恳请您准备一个可以通过其他方式使用OpenGLES 3.0的环境。
> > > 谢谢。
> > 
> > 
> > 我使用物理机环境运行顺利，也许还需要在vmware上做一些改装操作。谢谢您的解答！
> 
> 我使用物理机环境运行顺利，也许还需要在vmware上做一些适配操作。谢谢您的回答！

I have run smoothly using the physical machine environment, and perhaps I need to do some adaptation operations on vmware. Thank you for your answer!

**Comment by Vizdl** [comment]
> We have tested the operation of remote-virtio-gpu on native Ubuntu, but we have not verified its performance on VMware. Therefore, we cannot guarantee that remote-virtio-gpu will work on VMware.
> 
> RVGPU requires OpenGLES 3.0 or higher, but since the glmark2 results show "OpenGL 4.1," it seems that you cannot use OpenGLES 3.0 in your environment. Even if you execute the `sudo apt install libgles2-mesa-dev ` command mentioned in the README, if you still cannot use OpenGLES 3.0, there is a possibility that VMware does not support OpenGLES 3.0. In that case, we kindly ask you to prepare an environment where OpenGLES 3.0 can be utilized through alternative means.
> 
> Thank you.

I have run smoothly using the physical machine environment, and perhaps I need to do some adaptation operations on vmware. Thank you for your answer!
