### ISSUE TITLE
Some questions about rvgpu-proxy

### ISSUE THREAD

**Issue by HT-Yuan** [unified-hmi/remote-virtio-gpu#20]
- Hello, can I understand this project this way: the rvgpu-proxy can be deployed on a machine without a GPU, and the rvgpu-renderer must have a GPU.
-

**Comment by AtsuyaNasu** [comment]
Thank you for your message. Your understanding is correct.
Additionally, please note that the rvgpu-proxy can also operate on a machine with a GPU.

**Comment by HT-Yuan** [comment]
Can rvgpu-proxy work without an actual physical display? I tried to use xvfb to run "weston --backend drm-backend.so --tty=2 --seat=seat_virtual -i 0 " but it failed.
